spring:
  profiles:
    include: core
server:
  servlet:
    session:
      tracking-modes: cookie #이렇게 하면 url에 jessionId가 노출이 안된다, 예전에 url에 노출되서 난리난적이..
    context-path: /admin
  error:
    include-binding-errors: always
    include-message: always
  shutdown: graceful

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**
